#!/usr/bin/env bash
# セッションチェックポイント: Stop hook から呼び出される
# - 最新セッションサマリーを .claude/sessions/latest-summary.md に生成する

ROOT="$(git rev-parse --show-toplevel)"
SESSIONS_DIR="$ROOT/.claude/sessions"
SUMMARY_FILE="$SESSIONS_DIR/latest-summary.md"

mkdir -p "$SESSIONS_DIR"

cat > "$SUMMARY_FILE" << EOF
<!-- Auto-generated by session-checkpoint.sh. Do not edit manually. -->
<!-- Updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ") -->

## 直近セッションのコンテキスト

### 作業ブランチ
$(git branch --show-current)

### 最終コミット
$(git log --oneline -3)

### 未コミット変更
$(git status --short | head -20)

### TODOコメント（直近変更ファイル）
$(git diff --name-only HEAD~1 HEAD 2>/dev/null | xargs grep -n "TODO\|FIXME\|HACK" 2>/dev/null | head -20 || echo "なし")
EOF

# ──────────────────────────────────────────────
# 不変監査ログ（append-only。絶対に上書きしない）
# ──────────────────────────────────────────────
AUDIT_FILE="$ROOT/.claude/audit.jsonl"
mkdir -p "$(dirname "$AUDIT_FILE")"

# JSON を1行として追記（>> のみ使用。> は絶対に使わない）
TS="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
BRANCH="$(git branch --show-current)"
COMMIT="$(git log --oneline -1)"

if command -v jq >/dev/null 2>&1 && [ -f "$ROOT/.claude/state.json" ]; then
  IN_PROGRESS="$(jq -r '.in_progress // "null"' "$ROOT/.claude/state.json" 2>/dev/null || echo "null")"
  STATUS="$(jq -r '.status // "unknown"' "$ROOT/.claude/state.json" 2>/dev/null || echo "unknown")"
else
  IN_PROGRESS="null"
  STATUS="unknown"
fi

if command -v jq >/dev/null 2>&1; then
  jq -cn \
    --arg ts "$TS" \
    --arg branch "$BRANCH" \
    --arg commit "$COMMIT" \
    --arg in_progress "$IN_PROGRESS" \
    --arg status "$STATUS" \
    '{timestamp: $ts, branch: $branch, last_commit: $commit,
      in_progress: $in_progress, status: $status}' \
    >> "$AUDIT_FILE"
else
  # jq 未インストール時のフォールバック（JSON エスケープは簡易）
  escape() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }
  printf '{"timestamp":"%s","branch":"%s","last_commit":"%s","in_progress":"%s","status":"%s"}\n' \
    "$(escape "$TS")" "$(escape "$BRANCH")" "$(escape "$COMMIT")" \
    "$(escape "$IN_PROGRESS")" "$(escape "$STATUS")" \
    >> "$AUDIT_FILE"
fi
